version: '2'
services:
    jhipsteres-app:
        image: jhipsteres
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsteres-mysql:3306/jhipsteres?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhipsteres-elasticsearch:9300
        ports:
            - 8080:8080
    jhipsteres-mysql:
        extends:
            file: mysql.yml
            service: jhipsteres-mysql
    jhipsteres-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipsteres-elasticsearch
